### ISSUE TITLE
reaction rebranding

### ISSUE THREAD

**Issue by FeelsBadMan1** [Goose-Nest/GT-RevertRebrand#24]
Hello, is it possible to only revert a few options like keeping the new reactiondesign but everything else back to usual?

**Comment by Andrew6rant** [comment]
You could fork the repo and delete line 6 in src/main.scss and 79-123 in src/main.css. Change the url in RevertRebrand.theme.css to link to your repo

**Comment by mutageneral** [comment]
@FeelsBadMan1 
In your custom theme folder there is the CSS file of this theme. It is called ``RevertRebrand.theme.css``. BetterDiscord also has a built-in editor now so if that is what you are using you can go to the plugin section in the settings and search for "rebrand" and open it. Otherwise, you can open it in a text editor like notepad.

Now, let's look at what it looks like inside:
```css
/**
  * @name Revert Rebrand
  * @author GooseNest
  * @donate https://github.com/sponsors/CanadaHonk
  * @description Reverts Discord's 2021 rebrand (font, colors, reactions, mentions, loading screen, home icon, reply ping color, and more)
  * @invite neMncS2
  * @source https://Goose-Nest.github.io/GT-RevertRebrand/src/RevertRebrand.theme.css
  * @website https://github.com/Goose-Nest/GT-RevertRebrand
  * @version 4.0
*/

/* If you do not want some things reverted, commend out imports like /* @import url("...") */

/* [Recommended] Revert CSS variables: colors, fonts */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/variables.css');


/* Individual components: */

/* Revert mentions */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/components/mentions.css');

/* Revert reactions */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/components/reactions.css');

/* Revert profile pictures */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/components/pfps.css');

/* Revert folders (default colors back to old blurple) */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/components/folders.css');

/* Revert new user modals */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/components/oldUserModal.css');


/* General changes: */

/* Revert some BD specific elements */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/general/bd.css');

/* Revert some inputs */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/general/inputs.css');

/* Revert some SVGs (colors for smaller icons) */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/general/svgs.css');

/* Revert some other minor things */
@import url('https://Goose-Nest.github.io/GT-RevertRebrand/src/general/other.css');
```
Looks like the theme maker included a way to turn things on and off!
> If you do not want some things reverted, commend out imports like ``/* @import url("...")``

Look under "Individual components" for the "Revert reactions" line and comment out (To comment out a line add ``/*`` at the start and ``*/``  at the end of the line) or delete what is on the next line!

If this file gets updated by the theme maker you will have to do this again as it will replace your edit. Hopefully this will have helped you!

---
###### If you have any questions, ask me, Don't forget to close your issue when done.

**Comment by CanadaHonk** [comment]
Was changed a few days ago to use imports to be more modular (and thanks @mutageneral).
