### ISSUE TITLE
Profile alignment broken

### ISSUE THREAD

**Issue by asportnoy** [Goose-Nest/GT-RevertRebrand#30]
This theme breaks the alignment of the new profiles

Normal
![image](https://user-images.githubusercontent.com/14863373/119833509-c8ffb200-bec4-11eb-9fce-395a1693244d.png)

With revert theme:
![image](https://user-images.githubusercontent.com/14863373/119833474-c2713a80-bec4-11eb-98c2-36771d4fc595.png)

Ptb 86162 (70570e4)
BetterDiscord 1.1.1
Host 0.0.56
OS X 11.0.0 (20.6.0)

**Comment by mutageneral** [comment]
This is probably a PTB only problem because it is not happening to me.
![image](https://user-images.githubusercontent.com/62779748/119921895-cd67b180-bf3c-11eb-8dff-ba539a01faea.png)

**Comment by asportnoy** [comment]
Weird, it seems to have fixed itself. Not sure when that happened.

**Comment by asportnoy** [comment]
Nevermind, I apparently had the theme off when I was checking 😂 is still broken. Mine now has the nick centered too like in @mutageneral's screenshot but it's supposed to be left aligned as shown in my original post. If you disable the theme you'll see how it's supposed to be aligned.

**Comment by mutageneral** [comment]
@asportnoy
> Nevermind, I apparently had the theme off when I was checking 😂 is still broken. Mine now has the nick centered too like in @mutageneral's screenshot but it's supposed to be left aligned as shown in my original post. If you disable the theme you'll see how it's supposed to be aligned.

Oh okay. I did not understand you correctly on the first time. Read the following closely.

The user profiles cards aka user modals where reverted because it is a part of Discord's rebranding, and this add-ons is about reverting it! The rebranding is basically every change's discord do since they announced the rebranding. Discord are going to change pretty much everything until it becomes a completely new look, the rebranded look.

Rebrand  | Revert
------------- | -------------
![image](https://user-images.githubusercontent.com/62779748/119928565-cc894c80-bf49-11eb-923f-7f45c49e6025.png)    | ![image](https://user-images.githubusercontent.com/62779748/119928529-bda29a00-bf49-11eb-85a7-2664ed8fee6e.png)

Now it doesn't look exactly like the pre-rebrand look, but that's the subject of issue #29. I hope the theme maker will make it looks exactly how they used to look. 


Now, if you want to personally want to turn off the changes done to the user modals you can follow the tutorial I posted in issue #24. The only difference to the tutorial is that you need to find "Revert new user modals" instead of "Revert reactions". Don't worry, it is a very easy process. Hopefully this will have helped you!

---
###### If you have any questions, ask me. Don't forget to close your issue when done.

**Comment by CanadaHonk** [comment]
@asportnoy it has been made a part of the theme which will soon be disabled by default, thanks
